### ISSUE TITLE
I send 1981 burst Transaction #5323272026421703386, link: https://explore.burst.cryptoguru.org/transaction/5323272026421703386 but transaction not complete

### ISSUE THREAD

**Issue by hungtrinhburst** [PoC-Consortium/burstcoin-mobile#48]
If you have multiple feature requests, please create a seperate issue for each individual feature.
If you report a bug, please use the following template!

**Specifications**

  - Application Version: 0.2.2
  - Android Version: 8.1
  - Device: nokia 6 2018

**Expected Behavior**

**Actual Behavior & Screenshots**

**Steps to Reproduce the Problem**

  1.
  2.
  3.

**Comment by hungtrinhburst** [comment]
Please help me, thanks !

**Comment by cgebe** [comment]
It depends on whether your transactions gets included on a future block. I can see that it went through already, close this.

**Comment by cgebe** [comment]
[https://burstwiki.org/wiki/FAQ](https://burstwiki.org/wiki/FAQ)  - 3) Bittrex requires every deposit to include an un-encrypted message indicating which account is to be credited. Burst encrypts messages by default. If you did not deselect the encryption box, or did not include the required message, contact Bittrex support with all of the details and eventually they will credit your account. It is important to follow instructions carefully and to fully understand what you are doing at all times as it is possible to loose coins due to inadvertent errors such as this. 

Immediately contact the bittrex support, stating the transaction and ask for further actions.
